### ISSUE TITLE
Freezes the browser tab.

### ISSUE THREAD

**Issue by SrLicht** [cherninlab/breek#1]
When trying to load the game the tab will freeze and will not respond.

**Comment by cherninlab** [comment]
Thanks for reporting this
I'll update this thread once I have more information or a fix.

**Comment by cherninlab** [comment]
The freezing issue is likely caused by the game's heavy reliance on SVG SMIL animations. I will update this thread as soon as the fix is implemented.

**Comment by cherninlab** [comment]
The issue has been fixed in version 1.0.5 by replacing SVG SMIL animations with CSS animations.
The fix is now in production and can be seen in the `/packages/svg-creator/src/index.ts`
Closing this issue as resolved. 👍
